<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Actions' => 'Amallar',
    'Active' => 'Faol',
    'Address' => 'Manzil',
    'Are you sure you want to delete this item?' => 'Ushbu elementni o`chirishni xohlaysizmi?',
    'Box Header' => 'Sarlavha',
    'Boxed Layout' => 'Maket',
    'Child' => 'Bolasi',
    'Content' => 'Tarkib',
    'Content...' => 'Tarkib...',
    'Create User' => 'Foydalanuvchi yaratish',
    'Created At' => 'Yaratilgan vaqti:',
    'Created By' => 'Tomonidan yaratilgan',
    'Data' => 'Ma`lumotlar',
    'Delete' => 'O`chirish',
    'Description' => 'Tavsif',
    'ERROR' => '',
    'Email' => 'Elektron pochta',
    'Fixed Footer' => '',
    'Fixed Header' => '',
    'Fixed Left Menu' => '',
    'ID' => '#',
    'If you find this page, let us know.' => 'Agar siz ushbu sahifani topsangiz, bizga xabar bering.',
    'Inactive' => 'Faol emas',
    'Item Name' => '',
    'Layout Options' => '',
    'Logout' => 'Chiqish',
    'Name' => 'Nomi',
    'Online' => 'Onlayn',
    'Organization' => 'Sozlamalar',
    'Parent' => '',
    'Password' => 'Parol',
    'Permission not available!' => 'Ruxsat mavjud emas!',
    'Permissions' => 'Ruxsatlar',
    'Position' => 'Lavozim',
    'Profile' => 'Profil',
    'Remember Me' => 'Eslab qolish',
    'Reset' => 'Qayta o`rnatish',
    'Right-to-Left' => 'O`ngdan chapga',
    'Rule Name' => 'Qoida nomi',
    'Rules' => 'Qoidalar',
    'Save' => 'Saqlash',
    'Search' => 'Qidiruv',
    'Search ...' => 'Qidirish...',
    'Settings' => 'Sozlamalar',
    'Sign in' => 'Tizimga kirish',
    'Skin Color' => 'Ko`rinish rangi',
    'Status' => 'Holati',
    'The requested page does not exist.' => 'So`ralgan sahifa mavjud emas.',
    'Toggle navigation' => 'Navigatsiyani yoqing',
    'Type' => 'Tipi',
    'Update' => 'Tahrirlash',
    'Update User' => 'Foydalanuvchini tahrirlash',
    'Updated At' => 'Yangilangan vaqti:',
    'Updated By' => 'Tomonidan yangilangan',
    'User ID' => 'Foydalanuvchi',
    'Username' => 'Login',
    'Users' => 'Foydalanuvchilar',
    'View' => 'Ko`rish',
];
