<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Actions' => '',
    'Active' => '',
    'Address' => '',
    'Are you sure you want to delete this item?' => '',
    'Box Header' => '',
    'Boxed Layout' => '',
    'Child' => '',
    'Content' => '',
    'Content...' => '',
    'Create User' => '',
    'Create Users' => '@@@@',
    'Created At' => '',
    'Created By' => '',
    'Data' => '',
    'Delete' => '',
    'Description' => '',
    'ERROR' => '',
    'Email' => '',
    'Fixed Footer' => '',
    'Fixed Header' => '',
    'Fixed Left Menu' => '',
    'ID' => '',
    'If you find this page, let us know.' => '',
    'Inactive' => '',
    'Item Name' => '',
    'Layout Options' => '',
    'Logout' => '',
    'Name' => '',
    'Online' => '',
    'Organization' => '',
    'Parent' => '',
    'Password' => '',
    'Permission not available!' => '',
    'Permissions' => '',
    'Position' => '',
    'Profile' => '',
    'Reset' => '',
    'Right-to-Left' => '',
    'Rule Name' => '',
    'Rules' => '',
    'Save' => '',
    'Search' => '',
    'Search ...' => '',
    'Settings' => '',
    'Sign in' => '',
    'Skin Color' => '',
    'Status' => '',
    'The requested page does not exist.' => '',
    'Toggle navigation' => '',
    'Type' => '',
    'Update' => '',
    'Update User' => '',
    'Update Users: {name}' => '@@@@',
    'Updated At' => '',
    'Updated By' => '',
    'User ID' => '',
    'Username' => '',
    'Users' => '',
    'View' => '',
];
